// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2stLSNE9gMVRgOGQjA88u3-5OH1WYk1c',
    appId: '1:982890974352:web:fdd0e6a0fe7f4467809c15',
    messagingSenderId: '982890974352',
    projectId: 'receipt-tracker-4b348',
    authDomain: 'receipt-tracker-4b348.firebaseapp.com',
    storageBucket: 'receipt-tracker-4b348.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_cHkPkB1Pu4Kz6SkC_oRwGvjkOYkvVc',
    appId: '1:982890974352:android:1308057181cf7413809c15',
    messagingSenderId: '982890974352',
    projectId: 'receipt-tracker-4b348',
    storageBucket: 'receipt-tracker-4b348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtQOAeBv4G9Yt1XRVMkUTmr495D4un7g',
    appId: '1:982890974352:ios:ae4ac822cbdd9ada809c15',
    messagingSenderId: '982890974352',
    projectId: 'receipt-tracker-4b348',
    storageBucket: 'receipt-tracker-4b348.firebasestorage.app',
    iosClientId: '982890974352-04t0n083ai0tnlgphd3pv1ol5r9mgsjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtQOAeBv4G9Yt1XRVMkUTmr495D4un7g',
    appId: '1:982890974352:ios:ae4ac822cbdd9ada809c15',
    messagingSenderId: '982890974352',
    projectId: 'receipt-tracker-4b348',
    storageBucket: 'receipt-tracker-4b348.firebasestorage.app',
    iosClientId: '982890974352-04t0n083ai0tnlgphd3pv1ol5r9mgsjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2stLSNE9gMVRgOGQjA88u3-5OH1WYk1c',
    appId: '1:982890974352:web:a7fae859662ea596809c15',
    messagingSenderId: '982890974352',
    projectId: 'receipt-tracker-4b348',
    authDomain: 'receipt-tracker-4b348.firebaseapp.com',
    storageBucket: 'receipt-tracker-4b348.firebasestorage.app',
  );
}
